# Generated by Django 3.2.7 on 2021-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.IntegerField(choices=[(1, 'Boobs'), (2, 'Ass'), (3, 'Fuck')]),
        ),
    ]
