# Generated by Django 3.2.7 on 2021-09-11 05:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('home', '0003_auto_20210910_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.IntegerField(choices=[(1, 'Boobs'), (2, 'Ass'), (3, 'Fuck'), (4, 'Pussy')]),
        ),
    ]
