# Generated by Django 3.2.7 on 2021-09-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210914_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=50)),
                ('e', models.CharField(max_length=50)),
                ('t', models.TextField()),
            ],
        ),
    ]
