# Generated by Django 3.2.7 on 2021-09-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
    ]
